# Generated by Django 5.2.3 on 2025-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/'),
        ),
    ]
