# Generated by Django 5.2.3 on 2025-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(choices=[('ADMISION_ELECTIVA', 'Admisión electiva'), ('ADMISION_EMERGENCIA', 'Admisión emergencia'), ('ADMINISTRACION', 'Administración'), ('ARQUITECTURA', 'Arquitectura'), ('AUX_FARMACIA', 'Aux farmacia'), ('CAMARERAS', 'Camareras'), ('COBRANZA', 'Cobranza'), ('COMPRAS', 'Compras'), ('COMPRAS_FARMACIA', 'Compras farmacia'), ('CONTABILIDAD', 'Contabilidad'), ('COCINA', 'Cocina'), ('EMERGENCIA', 'Emergencia'), ('ESTERILIZACION', 'Esterilización'), ('ESTAR_ENFERMERIA', 'Estar enfermería'), ('ESTAR_ENFERMERIA_2', 'Estar enfermería 2'), ('FARMACIA', 'Farmacia'), ('FACTURACION', 'Facturación'), ('HISTORIAS_MEDICAS', 'Historias médicas'), ('MARKETING', 'Marketing'), ('PRESUPUESTO', 'Presupuesto'), ('PRESIDENCIA', 'Presidencia'), ('PROTOCOLO', 'Protocolo'), ('QUIROFANO', 'Quirofano'), ('REGENTE', 'Regente'), ('RECURSOS_HUMANOS', 'Recursos humanos'), ('SERVICIOS_GENERALES', 'Servicios generales'), ('TECNOLOGIA', 'Tecnología'), ('UCI', 'UCI'), ('UTIN', 'UTIN'), ('AUDITORA', 'Auditora')], max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
