# Generated by Django 5.2.3 on 2025-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_empleado_direccion_alter_empleado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, default='empleados/default.jpg', upload_to='empleados/'),
        ),
    ]
